### ISSUE TITLE
Identification of MKL build

### ISSUE THREAD

**Issue by cderemble** [conda-forge/scs-feedstock#47]
### Comment:

Hi,
A build with MKL has been recently pushed, which is great. I nonetheless can’t select this build other than specifying the exact build string in my requirements. Other packages have the MKL string somewhere in the build string so one can add a requirement on it. Would it be possible to have the same thing here ?

**Comment by h-vetinari** [comment]
Just add a requirement of `libblas =*=*mkl` to your requirements, and you will get the right flavour.

**Comment by cderemble** [comment]
That’s what I tried but it does not work: without specifying the exact build, I think the different packages are equivalent when solving the dependencies, and I don’t know how to tell conda to prefer one over the other

**Comment by cderemble** [comment]
More precisely, if you have the MKL linked blas installed, then it satisfies the requirements for both builds of scs: the one that requires MKL linked blas AND the one that just requires blas. So the dependency solver can just choose equally one of these 2 builds.

**Comment by h-vetinari** [comment]
> More precisely, if you have the MKL linked blas installed, then it satisfies the requirements for both builds of scs: the one that requires MKL linked blas AND the one that just requires blas. So the dependency solver can just choose equally one of these 2 builds.

Fair enough. Could you open a PR that changes the build string (or part of it) to either use `mkl` or `generic`?

**Comment by cderemble** [comment]
Done in #48
